### PR TITLE
Set main as index.js

### PR DESCRIPTION
**Pull request by cjsewell**
Resolves Failed to resolve entry for package "mui-nested-menu". The package may have incorrect main/module/exports specified in its package. when using with vite

### CODE REVIEW

**Comment by abelozerov** [comment]
Faced the same issue. Will this P/R be merged anytime soon?

**Comment by shubh24i** [comment]
I am facing the same issue. Please merge this P/R soon

**Comment by steviebaa** [comment]
I'll try get around to checking it out and testing it this weekend. 🤞

**Comment by shubh24i** [comment]
Thanks for your kind support
*   Sanjay Yadav*

Phone: +91-8310206130
Email: ***@***.***

**Comment by steviebaa** [comment]
Published to NPM as [2.1.4](https://www.npmjs.com/package/mui-nested-menu/v/2.1.4). Sorry for the delay on that one.

**Comment by shubh24i** [comment]
Thanks for your effort. It is appreciable

**Pull request merged**
